---
- name: Create Prometheus user
  import_tasks: create_user.yml

- name: Update hosts
  import_tasks: update_hosts.yml

- name: Install Prometheus
  import_tasks: install_prometheus.yml

- name: Secure Nginx
  import_tasks: secure_nginx.yml
