{
 "title": "Cosmos General",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "chain_id", "label": "Chain ID", "query": { "query": "label_values(chain_id)" } },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "stat",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Consensus Rounds At Current Height",
   "type": "stat",
   "description": "Number of rounds",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_rounds{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Transactions At Current Height",
   "type": "stat",
   "description": "Number of transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Confirmed Transactions",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "stat",
   "description": "Block size in bytes",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Block Time (seconds)",
   "type": "graph",
   "description": "Time between this and last block (Block.Header.Time) in seconds",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "STEAK" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  { "title": "Mempool Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Unconfirmed",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Rechecked",
   "type": "stat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Size (bytes)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_tx_size_bytes_count{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Byzantine",
   "type": "stat",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "% of (Missing+Byzantine)",
   "type": "stat",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", job=\"$server\"} + tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", job=\"$server\"}) / tendermint_consensus_validators_power{chain_id=\"$chain_id\", job=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Voting Power of Missing",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Voting Power of Byzantine",
   "type": "stat",
   "description": "Total voting power of the byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  },
  {
   "title": "Missing Validators History",
   "type": "graph",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", job=\"$server\"}"
    }
   ]
  }
 ]
}